venv_twentythree/accounts/urls.py
from django.conf.urls import url, include
from accounts import views


app_name = 'accounts'

urlpatterns = [
    url(r'^profile_block/$', views.block_user, name='block_user'),
    url(r'^$', views.create_user_form, name='registration'),
    url(r'^list/$', views.search_users, name='list'),
    url(r'^profile/$', views.edit_profile, name='profile'),
    url(r'^craeateprofile$', views.crate_user_profile, name='createprofile'),
    url(r'^list/(?P<pk>\d+)/$', views.user_detail_view, name='detail'),
    url(r'^list_messages/(?P<pk>\d+)/$', views.user_detail_messages_view, name='detail_messages'),
    url(r'^viewprofile/$', views.UserProfileView.as_view(), name='viewprofile'),
    url(r'^confirm-deactivate/$', views.ConfirmDeactivate.as_view(), name='confirm-deactivate'),
    url(r'^deactivate/$', views.delete_profile, name='deactivate'),
    url(r'^accountsapi/$', views.UsersListAPI.as_view()),
    url(r'^accountsapi/(?P<pk>\d+)/$', views.UsersDetailAPI.as_view(), name='api_detail'),
    url(r'^acoountsapi/(?P<pk>\d+)/update/$', views.UserUpdateAPI.as_view(), name='api_update'),

]

venv_twentythree/comments/urls.py
from django.conf.urls import url
from comments import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'comments'

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^todo/(?P<pk>\d+)/suggestion/$', views.add_suggestion_to_todo, name='add_suggestion_to_todo'),
    url(r'^commentsapi/$', views.CommentListAPI.as_view()),
    url(r'^commentsapi/(?P<pk>\d+)/$', views.CommentDetailSeri.as_view(), name='api_detail'),
    url(r'^commentsapi/(?P<pk>\d+)/update/$', views.CommentUpdateSeri.as_view(), name='api_update'),
    url(r'^commentsapi/(?P<pk>\d+)/delete/$', views.CommentDeleteSeri.as_view(), name='api_delete')

]

venv_twentythree/friends/urls.py
from django.conf.urls import url
from friends import views

app_name = 'friends'

urlpatterns = [
    url(r'^add/(?P<pk>\d+)/to_friends_list/$', views.add_friend_to_list, name='add_friend'),
    url(r'^view/(?P<username>[-\w]+)/friends_list/$', views.UserFriends.as_view(), name='my_list_friend'),
    url(r'^remove/(?P<pk>\d+)/$', views.delete, name='friend_remove'),

]

venv_twentythree/noti/urls.py
from django.conf.urls import url
from noti import views
app_name = 'noti'

urlpatterns = [
    url(r'^$', views.AllNotificationsList.as_view(), name='all'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete')
]

venv_twentythree/posts/urls.py
from django.conf.urls import url
from posts import views


app_name = 'posts'

urlpatterns = [
    url(r'^$', views.post_list_search, name='list'),
    url(r'^create_post/$', views.crate_post, name='create_post'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    # url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='single'),

    # url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),

    url(r'^post/(?P<pk>\d+)$', views.post_details, name='post_detail'),
    url(r'^like/$', views.like_post, name='like_post'),

    url(r'^postsapi/$', views.PostListSeri.as_view()),
    url(r'^postsapi/create/$', views.PostCreateAPIView.as_view()),
    url(r'^postsapi/(?P<pk>\d+)/$', views.PostDetailSeri.as_view(), name='api_detail'),
    url(r'^postsapi/(?P<pk>\d+)/update/$', views.PostUpdateSeri.as_view(), name='api_update'),
    url(r'^postsapi/(?P<pk>\d+)/delete/$', views.PostDeleteSeri.as_view(), name='api_delete')
]

venv_twentythree/todolist/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'todolist'

urlpatterns = [
    url(r'^$', views.world_todo_list, name='todo_list'),
    url(r'^my_todo$', views.addTodo, name='add'),
    url(r'^complete/(?P<pk>\d+)/$', views.complete_todo, name='complete'),
    url(r'^delete_complete/$', views.delete_completed, name='deletecomplete'),
    url(r'^delete_all/$', views.delete_all, name='deleteall'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserTodo.as_view(), name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.TodoDetailView.as_view(), name='single'),
    url(r'^remove/(?P<pk>\d+)/$', views.delete_individual_todo, name='remove_todo_individual'),


]

venv_twentythree/venv_twentythree/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('berenise90silvano90/', admin.site.urls),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^noti/', include('noti.urls', 'noti')),

    url(r'^group_message/', include('message_group.urls', namespace='group_message')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    url(r'^message/', include('mymessage.urls', namespace='message')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^todo/', include('todolist.urls', namespace='todo')),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^$', views.index_home.as_view(), name='home'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venv_twentythree/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profiles', on_delete=models.CASCADE)
    gender = models.CharField(max_length=20)
    description = models.TextField(max_length=200)
    profile_pic = models.ImageField(upload_to='media', blank=True)
    blocked_users = models.ManyToManyField('auth.User', related_name='blocked', blank=True, through='BlockedList')

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.pk})


class BlockedList(models.Model):
    profile = models.ForeignKey(Profile, related_name='members', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

venv_twentythree/accounts/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea, TextInput

class UserFormRegistration(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class UserFormProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('gender', 'description', 'profile_pic')


# -------------------------to update---------------------------------------

class UserFormProfileUpdate(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['description', 'profile_pic']

        widgets = {
            'description': Textarea(attrs={'cols': 80, 'rows': 4}),
        }


class UserFormCreationFormUpdate(forms.ModelForm):
    User._meta.get_field('email')._unique = True
    User._meta.get_field('username')._unique = True

    class Meta:
        model = User
        fields = ('username',)

        widgets = {
            'username': TextInput(attrs={'size': '20'})
        }

venv_twentythree/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, DeleteView, DetailView, CreateView, UpdateView, ListView
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from .forms import UserFormRegistration, UserFormProfile, UserFormCreationFormUpdate, UserFormProfileUpdate
from .models import Profile, BlockedList
from posts.models import MakePost
from todolist.models import Todo
from mymessage.models import MyMessage
from rest_framework.generics import ListAPIView, RetrieveAPIView, DestroyAPIView, UpdateAPIView, CreateAPIView, RetrieveUpdateAPIView
from rest_framework.permissions import IsAuthenticated, IsAdminUser, AllowAny, IsAuthenticatedOrReadOnly
from .serializers import UsersListSerializer, UsersDetailSerializer, UserUpdateSerializer
from .permissions import IsOwnerOrReadOnly
from rest_framework.filters import SearchFilter
from .pagination import PostLimitOffsetPagination
from itertools import chain
from notify.models import Notification

from operator import attrgetter
# class UsersListAPI(ListAPIView):
#     queryset = Profile.objects.all()
#     serializer_class = UsersListSerializer
#     permission_classes = [IsAuthenticated]


class UsersListAPI(ListAPIView, LoginRequiredMixin):
    serializer_class = UsersListSerializer
    filter_backends = [SearchFilter]
    search_fields = ['description', 'gender', 'user']  # to use this write (?gender= or ?user= or ?q=)
    pagination_class = PostLimitOffsetPagination

    def get_queryset(self, *args, **kwargs):
        queryset_list = Profile.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(Q(description__icontains=query) |
                                                 Q(gender__icontains=query) |
                                                 Q(user__last_name__icontains=query) |
                                                 Q(user__email__icontains=query) |
                                                 Q(user__first_name__icontains=query) |
                                                 Q(user__username__icontains=query)).distinct()
        return queryset_list


class UsersDetailAPI(RetrieveAPIView, LoginRequiredMixin):
    queryset = Profile.objects.all()
    serializer_class = UsersDetailSerializer


class UserUpdateAPI(RetrieveUpdateAPIView, LoginRequiredMixin):
    queryset = Profile.objects.all()
    serializer_class = UserUpdateSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

# ------------------------------------Views------------------------------------------------------


# @login_required
# def index_home(request):
#     posts = MakePost.objects.all()
#     metas = Todo.objects.all()
#
#     # both_lists = list(chain(posts, metas))
#     # paginator = Paginator(both_lists, 8)
#     # page = request.GET.get('page')
#     # pagination_list = paginator.get_page(page)
#
#     context = {
#         'post_list': posts,
#         'meta_list': metas,
#
#     }
#     return render(request, 'main.html', context)


class index_home(LoginRequiredMixin, ListView):
    login_url = '/login/'
    template_name = 'main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_list'] = MakePost.objects.all()
        context['meta_list'] = Todo.objects.all()
        context['notifications_list'] = Notification.objects.filter(deleted=False, recipient=self.request.user)
        return context

    def get_queryset(self):
        return MakePost.objects.all()


class ViewUserProfile(TemplateView, LoginRequiredMixin):
    template_name = 'accounts/profile.html'


def crate_user_profile(request):
    form = UserFormProfile()

    if request.method == "POST":
        form = UserFormProfile(data=request.POST, files=request.FILES)

        if form.is_valid():
            userprofile = form.save(commit=False)

            pic = form.cleaned_data['profile_pic']
            if not pic:
                userprofile.profile_pic = 'hummingbird.jpg'
            userprofile.user = request.user
            form.save(commit=True)

            return render(request, 'main.html')
        else:
            form = UserFormProfile()

    return render(request, 'accounts/profile.html', {'form': form})


def create_user_form(request):
    form = UserFormRegistration()

    if request.method == "POST":
        form = UserFormRegistration(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return render(request, 'main.html')
        else:
            form = UserFormRegistration()

    return render(request, 'registration/form.html', {'form': form})


@login_required
def search_users(request):
    queryset_list = {}

    query = request.GET.get('q')
    if query is not None:
        queryset_list = Profile.objects.all().exclude(user=request.user)
        queryset_list = queryset_list.filter(
            Q(user__first_name=query) | Q(user__username=query) | Q(user__last_name=query) | Q(user__email=query))

    context = {
        "object_list": queryset_list
    }
    return render(request, 'search_users/index.html', context)


@login_required
def user_detail_view(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    is_blocked = False

    if BlockedList.objects.filter(user=profile.user, profile=request.user.profiles):
        is_blocked = True
    context = {
        'user_list': profile,
        'is_blocked': is_blocked,
        'post_list': MakePost.objects.filter(author=profile.user),
        'todo_list': Todo.objects.filter(user=profile.user),
        'messages_list': MyMessage.objects.all().order_by('created_date')
    }
    return render(request, 'accounts/user_detail.html', context)


@login_required
def user_detail_messages_view(request, pk):
    profile = get_object_or_404(Profile, pk=pk)
    search_user = MyMessage.objects.filter(author=profile.user, recipient=request.user.profiles)
    request_user = MyMessage.objects.filter(author=request.user, recipient=profile)

    is_blocked = False

    if BlockedList.objects.filter(user=profile.user, profile=request.user.profiles):
        is_blocked = True

    result_list = sorted(
        chain(search_user, request_user),
        key=lambda instance: instance.created_date)

    context = {
        'is_blocked': is_blocked,
        'user_list': profile,
        'both_lists': result_list
    }
    return render(request, 'accounts/user_detail_messages.html', context)


@login_required
def edit_profile(request):
    image = request.user.profiles.profile_pic

    if request.method == 'POST':
        form1 = UserFormCreationFormUpdate(request.POST, instance=request.user)
        form2 = UserFormProfileUpdate(request.POST, request.FILES, instance=request.user.profiles)

        if form1.is_valid() and form2.is_valid():
            form1.save(commit=True)
            form2.save(commit=True)
            return redirect('home')
    else:
        form1 = UserFormCreationFormUpdate(instance=request.user)
        form2 = UserFormProfileUpdate(instance=request.user.profiles)


    return render(request, 'accounts/createprofile.html', {'form': form1, 'formm': form2, 'image': image})


class UserProfileView(TemplateView, LoginRequiredMixin):
    template_name = 'accounts/view_profile.html'


class ConfirmDeactivate(TemplateView, LoginRequiredMixin):
    template_name = 'profile/confirm_deactivate.html'


@login_required
def delete_profile(request):
    user = request.user
    user.is_active = False
    user.save()
    messages.success(request, 'Profile successfully disabled.')
    return redirect('home')


@login_required
def block_user(request):
    profile = get_object_or_404(Profile, pk=request.POST.get('post_id'))
    member = BlockedList.objects.filter(user=profile.user, profile=request.user.profiles)
    if member:
        member.delete()

    else:
        BlockedList.objects.create(user=profile.user, profile=request.user.profiles)
    return redirect(profile.get_absolute_url())

venv_twentythree/accounts/templates/accounts/createprofile.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% load bootstrap4 %}

{% block serach_block %}
{% endblock %}

{% block body_block %}


    <div class="container">
    <div class="jumbotron">
    <form method="post" enctype="multipart/form-data" >

        <p class="text-center">Update Profile</p>
        {% csrf_token %}

        <div class="row">
            <div class="col-6 col-sm-4">
                <label for="{{ form.username.id_for_label }}">Username: {{ form.username }}</label>
            </div>
            <div class="col-6 col-sm-4">
                <label for="{{ formm.description.id_for_label }}">Description: {{ formm.description }}</label>
            </div>
        </div>

        <img src="{{ image.url }}" style="width: 160px; height: 200px; object-fit: cover"><br>


        <label for="{{ formm.profile_pic.id_for_label }}">{{ formm.profile_pic }}</label><br>
        <img id="image" style="width: 160px; height: 200px; object-fit: cover"><br>

        <button type="submit" class="btn btn-dark">Submit</button>

    </form>
        </div>
</div>

{% endblock %}

venv_twentythree/accounts/templates/accounts/password_reset.html
<!DOCTYPE html>
{% extends "main.html" %}
{% block body_block %}

<div class="container">
<div class="jumbotron">
    <div align="center">



        <form method="POST">
            {% csrf_token %}
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form }}
                <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
        </form>

        </div>
</div>
</div>
{% endblock body_block %}

venv_twentythree/accounts/templates/accounts/password_reset_complete.html
<!DOCTYPE html>
{% extends "main.html" %}
{% block body_block %}
        Your password has been set.
    <a href="{% url 'login' %}">Sign In Here</a>
{% endblock body_block %}

venv_twentythree/accounts/templates/accounts/password_reset_confirm.html
<!DOCTYPE html>
{% extends "main.html" %}
{% block body_block %}
        <form method="POST">
            {% csrf_token %}
                <legend class="border-bottom mb-4">Reset Password</legend>
                {{ form }}
                <button class="btn btn-outline-info" type="submit">Reset Password</button>
        </form>
{% endblock body_block %}

venv_twentythree/accounts/templates/accounts/password_reset_done.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block body_block %}
    <p>An email has been sent with instructions to reset your password</p>
{% endblock body_block %}

venv_twentythree/accounts/templates/accounts/user_detail.html
<!DOCTYPE html>
{% extends 'main.html' %}

{% block serach_block %}
{% endblock %}

{% block body_block%}


{% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}


<div class="d-flex justify-content-center">


    <div class="card text-white bg-dark mb-3" style="width: 18rem;">
    {% if user_list.profile_pic %}
            <img class="card-img-top silvano" src="{{ user_list.profile_pic.url }}" alt="Card image cap">
    {% endif %}
            <div class="card-body">
                <p class="card-text">username: {{ user_list.user.username }}</p>
                <p class="card-text">description: {{ user_list.description }}</p>
                <div class="card-text">
                    <div class="btn-group" role="group" aria-label="Basic example">
                        {% if request.user in user_list.blocked_users.all or user_list.user in request.user.profiles.blocked_users.all%}
                            <p>You can not message this user or add it to your friends list</p>
                        {% else %}
                            <a href="{% url 'message:add_message' pk=user_list.pk %}" class="btn btn-outline-primary">Message</a>

                            <form method="POST" action="{% url 'friends:add_friend' pk=user_list.pk %}">
                                {% csrf_token %}
                                {{ form }}
                                <input class="btn btn-outline-success" type="submit" value="add friend">
                            </form>
                        {% endif %}
                    </div>
                </div>
                <br>
                <form method="POST" action="{% url 'accounts:block_user' %}">
                    {% csrf_token %}
                    {% if is_blocked %}
                        <button type="submit" class="btn btn-light" name="post_id" value="{{ user_list.pk }}">Unblock</button>
                    {% else %}
                        <button type="submit" class="btn btn-outline-danger" name="post_id" value="{{ user_list.pk }}">Block</button>
                    {% endif %}
                </form>


            </div>
    </div>

</div>





    <br>

<div class="jumbotron">

<div class="d-flex justify-content-center">

    <h1>Posts</h1>
</div>
    <br>

    <div class="row">

    {% for posts in post_list %}
<div class="col-md-4">

        <div class="card bg-light mb-3">
            {% if posts.post_pic %}
            <img class="card-img-top silvano" src="{{ posts.post_pic.url }}" alt="Card image cap">
            <div class="card-body">
                <h5 class="text-center"><a href="{% url 'posts:post_detail' pk=posts.pk %}">{{ posts.title }}</a></h5>
                <p class="card-text">{{ posts.created_date }}</p>
            </div>
            <div class="footer">
                <small class="text-muted"><a href="{% url 'comments:add_comment_to_post' pk=posts.pk %}" class="btn btn-light">Add Comment</a></small>
                <small class="text-muted">{{ posts.likes.count }} Like{{ posts.likes.count|pluralize }}</small>
                <small class="text-muted">{{ posts.comments.count }} comment{{ posts.comments.count|pluralize }}</small>
            </div>
            {% else %}
        <div class="card-body">
                <h5 class="text-center"><a href="{% url 'posts:post_detail' pk=posts.pk %}">{{ posts.title }}</a></h5>
                <p class="card-text">{{ posts.post_info_summary }}</p>
                <p class="card-text">{{ posts.created_date }}</p>
            </div>
            <div class="footer">
                <small class="text-muted"><a href="{% url 'comments:add_comment_to_post' pk=posts.pk %}" class="btn btn-light">Add Comment</a></small>
                <small class="text-muted">{{ posts.likes.count }} Like{{ posts.likes.count|pluralize }}</small>
                <small class="text-muted">{{ posts.comments.count }} comment{{ posts.comments.count|pluralize }}</small>
            </div>
{% endif %}

        </div>
            </div>
        {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div><div class="row">
        {% endif %}

    {% endfor %}
    </div>

</div>

<br>


<div class="jumbotron">
<div class="d-flex justify-content-center">

    <h1>Metas</h1>
</div>
    <br>
    <div class="row">
    {% for todo in todo_list %}
        <div class="col-md-4">
            <div class="card bg-light mb-3">
                {% if todo.todo_pic %}
                    <img class="card-img-top silvano" src="{{ todo.todo_pic.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="text-center"><a href="{% url 'todo:single' username=todo.user.username pk=todo.id %}">{{ todo.title }}</a></h5>
                        <p class="card-text">{{ todo.created_date }}</p>
                    </div>
                    <div class="footer">
                        <small class="text-muted"><a href="{% url 'comments:add_suggestion_to_todo' pk=todo.pk %}" class="btn btn-light">Add Suggestion</a></small>
                        <small class="text-muted">{{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}</small>
                    </div>
                {% else %}
                <div class="card-body">
                        <h5 class="text-center"><a href="{% url 'todo:single' username=todo.user.username pk=todo.id %}">{{ todo.title }}</a></h5>
                        <p class="card-text">{{ todo.meta_info_summary }}</p>
                        <p class="card-text">{{ todo.created_date }}</p>
                    </div>
                    <div class="footer">
                        <small class="text-muted"><a href="{% url 'comments:add_suggestion_to_todo' pk=todo.pk %}" class="btn btn-light">Add Suggestion</a></small>
                        <small class="text-muted">{{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}</small>
                    </div>
                    {% endif %}
            </div>
        </div>
        {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div><div class="row">
        {% endif %}

    {% endfor %}
               </div>

</div>


{% endblock %}

venv_twentythree/accounts/templates/accounts/user_detail_messages.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% block body_block%}

<div class="d-flex justify-content-center">

    <div>
        {% if user_list.profile_pic %}

            <img src="{{ user_list.profile_pic.url }}" width="240px">
            <br>
            <br>
            <p>username: {{ user_list.user.username }}</p>
            <p>description: {{ user_list.description }}</p>
            <p>gender: {{ user_list.gender }}</p>
            <form method="POST" action="{% url 'accounts:block_user' %}">
                {% csrf_token %}
                    {% if is_blocked %}
                        <button type="submit" class="btn btn-light" name="post_id" value="{{ user_list.pk }}">Unblock</button>
                    {% else %}
                        <button type="submit" class="btn btn-outline-danger" name="post_id" value="{{ user_list.pk }}">Block</button>
                    {% endif %}
            </form>
            <br>

        {% endif %}
    </div>
</div>
    <br>


{% if request.user not in user_list.blocked_users.all and user_list.user not in request.user.profiles.blocked_users.all%}

    {% for mm in both_lists %}


        <div class="row justify-content-center">
    <div class="col-4">
        {% if request.user == mm.author%}
            <p class="p-3 mb-2 bg-light text-dark">{{ mm.author }}:  <strong>{{ mm.text }}</strong></p>
            {% if mm.picture %}
                <img src="{{ mm.picture.url }}" style="width: 100%; height: auto;">
            {% endif %}
        {% endif %}
    </div>
    <div class="col-4">
        {% if user_list.user == mm.author%}
            <p class="p-3 mb-2 bg-dark text-white">{{ mm.author }}:  <strong>{{ mm.text }}</strong></p>
            {% if mm.picture %}
                <img src="{{ mm.picture.url }}" style="width: 100%; height: auto;">
            {% endif %}
        {% endif %}
    </div>
  </div>


    {% endfor %}

    {% if both_lists %}

    <div class="d-flex justify-content-center">
    <a href="{% url 'message:add_message' pk=user_list.pk %}" class="btn btn-primary">Respond</a>
    </div>

    {% else %}
        <div class="container">
            <div class="jumbotron">
                <div align="center">
                     <p><strong>No Messages</strong></p>
                </div>
            </div>
        </div>

    {% endif %}
{% else %}
    <div class="container">
        <div class="jumbotron">
            <div align="center"><p>Either you blocked {{ user_list.user }} or {{ user_list.user }} blocked you </p></div>
        </div>
    </div>

    {% endif %}

{% endblock %}

venv_twentythree/accounts/templates/accounts/user_list.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% block body_block%}

    <form method="GET" action="{% url 'accounts:list'%}" class="form-inline">

        {% csrf_token %}
        <div class="input-group input-group-lg">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroup-sizing-lg">Search users</span>
  </div>
  <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="q">
            <button type="submit" class="btn btn-dark">GO</button>

</div>

    </form>




    {% for user in object_list %}
        <a href="{{user.id}}">{{ user.user }}</a> <br>
    {% endfor %}

{% endblock %}