venv_twentythree/accounts/urls.py
from django.conf.urls import url, include
from accounts import views


app_name = 'accounts'

urlpatterns = [
    url(r'^profile_block/$', views.block_user, name='block_user'),
    url(r'^$', views.create_user_form, name='registration'),
    url(r'^list/$', views.search_users, name='list'),
    url(r'^profile/$', views.edit_profile, name='profile'),
    url(r'^craeateprofile$', views.crate_user_profile, name='createprofile'),
    url(r'^list/(?P<pk>\d+)/$', views.user_detail_view, name='detail'),
    url(r'^list_messages/(?P<pk>\d+)/$', views.user_detail_messages_view, name='detail_messages'),
    url(r'^viewprofile/$', views.UserProfileView.as_view(), name='viewprofile'),
    url(r'^confirm-deactivate/$', views.ConfirmDeactivate.as_view(), name='confirm-deactivate'),
    url(r'^deactivate/$', views.delete_profile, name='deactivate'),
    url(r'^accountsapi/$', views.UsersListAPI.as_view()),
    url(r'^accountsapi/(?P<pk>\d+)/$', views.UsersDetailAPI.as_view(), name='api_detail'),
    url(r'^acoountsapi/(?P<pk>\d+)/update/$', views.UserUpdateAPI.as_view(), name='api_update'),

]

venv_twentythree/comments/urls.py
from django.conf.urls import url
from comments import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'comments'

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^todo/(?P<pk>\d+)/suggestion/$', views.add_suggestion_to_todo, name='add_suggestion_to_todo'),
    url(r'^commentsapi/$', views.CommentListAPI.as_view()),
    url(r'^commentsapi/(?P<pk>\d+)/$', views.CommentDetailSeri.as_view(), name='api_detail'),
    url(r'^commentsapi/(?P<pk>\d+)/update/$', views.CommentUpdateSeri.as_view(), name='api_update'),
    url(r'^commentsapi/(?P<pk>\d+)/delete/$', views.CommentDeleteSeri.as_view(), name='api_delete')

]

venv_twentythree/noti/urls.py
from django.conf.urls import url
from noti import views
app_name = 'noti'

urlpatterns = [
    url(r'^$', views.AllNotificationsList.as_view(), name='all'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete')
]

venv_twentythree/posts/urls.py
from django.conf.urls import url
from posts import views


app_name = 'posts'

urlpatterns = [
    url(r'^$', views.post_list_search, name='list'),
    url(r'^create_post/$', views.crate_post, name='create_post'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    # url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='single'),

    # url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),

    url(r'^post/(?P<pk>\d+)$', views.post_details, name='post_detail'),
    url(r'^like/$', views.like_post, name='like_post'),

    url(r'^postsapi/$', views.PostListSeri.as_view()),
    url(r'^postsapi/create/$', views.PostCreateAPIView.as_view()),
    url(r'^postsapi/(?P<pk>\d+)/$', views.PostDetailSeri.as_view(), name='api_detail'),
    url(r'^postsapi/(?P<pk>\d+)/update/$', views.PostUpdateSeri.as_view(), name='api_update'),
    url(r'^postsapi/(?P<pk>\d+)/delete/$', views.PostDeleteSeri.as_view(), name='api_delete')
]

venv_twentythree/venv_twentythree/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('berenise90silvano90/', admin.site.urls),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^noti/', include('noti.urls', 'noti')),

    url(r'^group_message/', include('message_group.urls', namespace='group_message')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    url(r'^message/', include('mymessage.urls', namespace='message')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^todo/', include('todolist.urls', namespace='todo')),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^$', views.index_home.as_view(), name='home'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venv_twentythree/posts/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


class MakePost(models.Model):
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=63)
    post_pic = models.ImageField(upload_to='media', blank=True)
    info = models.TextField(max_length=3000)
    likes = models.ManyToManyField('auth.User', related_name='likes', blank=True, through='LikeUserList')
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def post_info_summary(self):
        len_info = len(self.info)
        if len_info > 480:
            return self.info[:480]+' . . . .continue'
        else:
            return self.info

    def get_absolute_url(self):
        return reverse('posts:post_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-created_date']


class LikeUserList(models.Model):
    post = models.ForeignKey(MakePost, related_name='members', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

venv_twentythree/posts/forms.py
from django import forms
from .models import MakePost
from django.forms import Textarea, TextInput, ImageField


class MakePostForm(forms.ModelForm):

    class Meta:
        model = MakePost
        fields = ['title', 'post_pic', 'info']

        widgets = {
            'info': Textarea(attrs={'cols': 140, 'rows': 6, 'placeholder': 'info'}),
            'title': TextInput(attrs={'size': '55'})
        }

venv_twentythree/posts/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.views.generic import TemplateView, DeleteView, DetailView, CreateView, UpdateView, ListView
from django.db.models import Q
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from .forms import MakePostForm
from .models import MakePost, LikeUserList
from comments.models import Comment
from .serializers import PostListSerializer, PostDetailSerializer, PostUpdateSerializer, PostCreateSerializer
from rest_framework.generics import ListAPIView, RetrieveAPIView, DestroyAPIView, UpdateAPIView, CreateAPIView, RetrieveUpdateAPIView
from rest_framework.permissions import IsAuthenticated, IsAdminUser, AllowAny, IsAuthenticatedOrReadOnly
from rest_framework.filters import SearchFilter
from .permissions import IsOwnerOrReadOnly
from django.db.models import Q
from accounts.pagination import PostLimitOffsetPagination
from notify.signals import notify
from django.contrib.auth import get_user_model
from django.http import Http404
User = get_user_model()


class PostListSeri(ListAPIView, LoginRequiredMixin):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter]
    search_fields = ['title', 'info']  # to use this write (?search=)
    pagination_class = PostLimitOffsetPagination

    def get_queryset(self, *args, **kwargs):
        queryset_list = MakePost.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(Q(info__icontains=query) |
                                                 Q(title__icontains=query)).distinct()
        return queryset_list


class PostDetailSeri(RetrieveAPIView, LoginRequiredMixin):
    queryset = MakePost.objects.all()
    serializer_class = PostDetailSerializer


class PostUpdateSeri(RetrieveUpdateAPIView, LoginRequiredMixin):
    queryset = MakePost.objects.all()
    serializer_class = PostUpdateSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]


class PostDeleteSeri(DestroyAPIView, LoginRequiredMixin):
    queryset = MakePost.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]


class PostCreateAPIView(CreateAPIView, LoginRequiredMixin):
    queryset = MakePost.objects.all()
    serializer_class = PostCreateSerializer

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)


@login_required
def crate_post(request):
    form = MakePostForm()

    if request.method == "POST":
        form = MakePostForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            user_post = form.save(commit=False)
            user_post.author = request.user
            form.save(commit=True)
            return redirect('posts:list')
        else:
            form = MakePostForm()

    return render(request, 'posts/makepost_form.html', {'form': form})


@login_required
def post_details(request, pk):
    post = get_object_or_404(MakePost, pk=pk)
    is_liked = False

    if LikeUserList.objects.filter(user=request.user, post=post.pk):
        is_liked = True
    context = {
        'comment_list': Comment.objects.all().order_by('-created_date'),
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def like_post(request):
    is_liked = False
    post = get_object_or_404(MakePost, id=request.POST.get('post_id'))
    membership = LikeUserList.objects.filter(user=request.user, post=post.pk)
    if membership:
        membership.delete()
        is_liked = False

    else:
        notify.send(sender=request.user, actor=request.user, recipient=post.author, verb="liked your post: ' {a} '. ".format(a=post.title),
                    nf_type='followed_by_one_user')

        LikeUserList.objects.create(user=request.user, post=post)
        is_liked = True
    return redirect(post.get_absolute_url())


class PostUpdateView(UpdateView, LoginRequiredMixin):
    form_class = MakePostForm
    success_url = reverse_lazy('posts:postlist')
    model = MakePost


class PostDeleteView(DeleteView, LoginRequiredMixin):
    model = MakePost
    success_url = reverse_lazy('posts:list')


class UserPosts(ListView, LoginRequiredMixin):

    context_object_name = 'post_list'
    model = MakePost
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context


@login_required
def post_list_search(request):

    queryset_list = MakePost.objects.all()

    query = request.GET.get('q')
    if query is not None:
        queryset_list = queryset_list.filter(Q(title__icontains=query) | Q(info__icontains=query))

    paginator = Paginator(queryset_list, 6)    # Show 25 contacts per page

    page = request.GET.get('page')
    queryset = paginator.get_page(page)

    context = {
        "post_list": queryset
    }
    return render(request, 'posts/post_list.html', context)

venv_twentythree/posts/templates/posts/_post.html
<!DOCTYPE html>


<div class="container">

    <div class="card text-white bg-dark mb-3">
    {% if post.post_pic %}
        <img class="card-img-top" src="{{ post.post_pic.url }}" alt="Card image cap">
    {% endif %}
        <div class="card-body">
            <p class="text-center" style="color: #afd9ee">{{ post.title }}</p>
            <p class="card-text">{{ post.info }}</p>
            <p class="card-title"><a href="{% url 'posts:for_user' username=post.author.username %}">@{{ post.author.username }}</a></p>
            <p class="card-text">Published on: {{post.created_date|date:"D M Y"}}</p>
            <div class="card-text">
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'comments:add_comment_to_post' pk=post.pk %}" class="btn btn-light">Add Comment</a>

                    <form method="POST" class="post-form" action="{% url 'posts:like_post' %}">
                        {% csrf_token %}
                        {% if is_liked %}
                            <button type="submit" class="btn btn-primary" name="post_id" value="{{ post.id }}">Unlike</button>
                        {% else %}
                            <button type="submit" class="btn btn-primary" name="post_id" value="{{ post.id }}">Like</button>
                        {% endif %}

                    </form>

                </div>
            </div>

            {% if user.is_authenticated and post.author == user %}
                <br>
                <p class="card-text"><a href="{% url 'posts:post_remove' pk=post.pk%}" class="btn btn-outline-danger">Delete</a></p>
            {% endif %}
        </div>
        <div class="card-footer text-muted">
            {{ total_likes }} Like{{ total_likes|pluralize }}
            {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
        </div>
    </div>


</div>



<div class="container">
    <div class="row">

        <div class="col">
            <div class="jumbotron">
                {% if post.members.count %}

                <div class="row">
                    {% for x in post.members.all %}
                        <div class="col-md-4">
                        <br>

                        {% if x.user.profiles.profile_pic %}

                            <div class="card" style="width: 10rem; height: 18rem">
                              <img class="card-img-top likepic" src="{{ x.user.profiles.profile_pic.url }}" alt="Card image cap">
                              <div class="card-body">
                                  {% if request.user != x.user %}
                                <h5 class="card-title"><a href="{% url 'accounts:detail' pk=x.user.profiles.id %}">{{ x }}</a></h5>
                                      {% else %}
                                <h5 class="card-title">{{ x }}</h5>

                                      {% endif %}

                              </div>
                            </div>
                        {% endif %}

                        <br>
                        <br>
                        </div>{% if forloop.counter|divisibleby:"3" and not forloop.last %}
                </div>
                <div class="row">
                                {% endif %}

                    {% endfor %}
                </div>
                {% else %}
                    <div class="container">
                        <div align="center">
                            <p><strong>No Likes</strong></p>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>

<br>
<br>
      <div class="col">
            <div class="jumbotron">
            <div align="center">
                {% if post.comments.count %}

                    <h3>Comments</h3>
                    {% for comments in comment_list %}
                        {% if comments.post == post %}

                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    {% if request.user != comments.author %}
                                    <p class="card-text"><a href="{% url 'accounts:detail' pk=comments.author.profiles.pk %}">{{ comments.author }}</a> </p>
                                        {% else %}
                                        <p>{{ comments.author }}</p>
                                        {% endif %}
                                    <p class="card-text">{{ comments.text }}</p>
                                </div>
                                <div class="card-footer text-muted"><p>Date: {{ comments.created_date }}</p>
                                </div>
                            </div>


                        {% endif %}
                        <br>

                    {% endfor %}
                {% else %}
                    <div class="container">
                        <div align="center">
                            <p><strong>No Comments</strong></p>
                        </div>
                    </div>
                {% endif %}

            </div>
            </div>
      </div>


  </div>
</div>

venv_twentythree/posts/templates/posts/makepost_confirm_delete.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}
        <div class="container">
        <div class="jumbotron">
            <div class="d-flex justify-content-center">

  <form method="post">

      {% csrf_token %}
      <p>Are you sure you want to delete {{object}}?</p>
      <button type="submit" class="btn btn-danger">Delete</button>

  </form>
            </div>
        </div>
        </div>

{% endblock %}

venv_twentythree/posts/templates/posts/makepost_form.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% load bootstrap4 %}
{% block body_block %}

{% block serach_block %}
{% endblock %}

<div class="container">
        <div class="jumbotron">
    <div class="container">

    <form method="post" enctype="multipart/form-data" >

        <p class="text-center">Create Post</p>
        {% csrf_token %}
{#        {% bootstrap_form form %}#}
{#        <button type="submit" class="btn btn-dark">Create</button>#}


        <div class="form-group">
            <label for="{{ form.title.id_for_label }}">Title: {{ form.title }}</label>
            <label for="{{ form.post_pic.id_for_label }}"><input onchange="PreviewImage();" type="file" id="files" value="{{ form.post_pic }}"></label>
            <img id="image" style="width: 170px; height: 200px; object-fit: cover" />
        </div>


            <p>{{ form.info }}</p>

            <button type="submit" class="btn btn-dark">Create</button>
        </form>

    </form>
        </div>
</div>
</div>


 <script type="text/javascript">
        document.getElementById("files").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};
    </script>


{% endblock %}

venv_twentythree/posts/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}
    {% include "posts/_post.html" %}
{% endblock %}

venv_twentythree/posts/templates/posts/post_list.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block body_block %}

<div class="jumbotron">


<div class="d-flex justify-content-center">

    <form method="GET" action="{% url 'posts:list'%}" class="form-inline">
        {% csrf_token %}
        <div class="input-group input-group-lg">
        <div class="input-group-prepend">
            <span class="input-group-text" id="inputGroup-sizing-lg">Search Posts</span>
        </div>
        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="q">
        <button type="submit" class="btn btn-dark">GO</button>
        </div>
    </form>

</div>

    <br>


    <div class="row">

    {% for post in post_list %}

<div class="col-md-4">
                <div class="card text-white bg-dark mb-3">
                    {% if post.post_pic %}
                        <img class="card-img-top silvano" src="{{ post.post_pic.url }}" alt="Card image cap">
                        <div class="card-body">
                            <p class="text-center"><a href="{% url 'posts:post_detail' pk=post.id %}">{{ post.title }}</a></p>
                            <p class="card-text"><a href="{% url 'posts:for_user' username=post.author.username %}">@{{ post.author.username }}</a></p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ post.likes.count }} Like{{ post.likes.count|pluralize }}
                            {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
                        </div>
                    {% else %}
                        <div class="card-body">
                            <p class="text-center"><a href="{% url 'posts:post_detail' pk=post.id %}">{{ post.title }}</a></p>
                            <p class="card-text">{{ post.post_info_summary }}</p>
                            <p class="card-text"><a href="{% url 'posts:for_user' username=post.author.username %}">@{{ post.author.username }}</a></p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ post.likes.count }} Like{{ post.likes.count|pluralize }}
                            {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div><div class="row">
        {% endif %}



{% endfor %}

           </div>

<div class="d-flex justify-content-center">

        <div class="pagination">

    {% if post_list.has_other_pages %}

    {% if post_list.has_previous %}
      <a href="?page={{ post_list.previous_page_number }}" class="pagination_numbers">&laquo;</a>

    {% else %}
      <div class="disabled pagination_numbers"><span>&laquo;</span></div>

    {% endif %}

    {% for i in post_list.paginator.page_range %}

      {% if post_list.number == i %}
        <div class="pagination_numbers"><span> {{ i }} </span></div>


      {% else %}
        <a href="?page={{ i }}" class="pagination_numbers">{{ i }}</a>

      {% endif %}
    {% endfor %}

    {% if post_list.has_next %}
      <a href="?page={{ post_list.next_page_number }}" class="pagination_numbers">&raquo;</a>

    {% else %}
      <div class="disabled pagination_numbers"><span>&raquo;</span></div>

    {% endif %}


{% endif %}
    </div>

</div>
</div>

{% endblock %}

venv_twentythree/posts/templates/posts/user_post_list.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}

<div class="jumbotron">
    {% if post_list %}

<div class="d-flex justify-content-center">

    <h2>All posts from {{ post_user }}</h2>
    <br>
</div>

    <div class="row">

        {% for post in post_list %}

            <div class="col-md-4">
                <div class="card text-white bg-dark mb-3">
                    {% if post.post_pic %}
                        <img class="card-img-top silvano" src="{{ post.post_pic.url }}" alt="Card image cap">
                        <div class="card-body">
                            <p class="text-center"><a href="{% url 'posts:post_detail' pk=post.id %}">{{ post.title }}</a></p>
                            <p class="card-text">Published on: {{post.created_date|date:"D M Y"}}</p>
                            <div class="card-text">
                                <div class="btn-group" role="group" aria-label="Basic example">
                                {% if user.is_authenticated and post.author == user %}
                                    <a href="{% url 'posts:post_remove' pk=post.pk%}" class="btn btn-outline-danger">Delete</a>
                                    <a href="{% url 'posts:post_edit' pk=post.pk%}" class="btn btn-outline-info">Edit</a>
                                {% endif %}
                                </div>
                            </div>
                            <br>
                            <p class="card-text"><a href="{% url 'comments:add_comment_to_post' pk=post.pk %}" class="btn btn-light">Add Comment</a></p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ post.likes.count }} Like{{ post.likes.count|pluralize }}
                            {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
                        </div>
                    {% else %}
                        <div class="card-body">
                            <p class="text-center"><a href="{% url 'posts:post_detail' pk=post.id %}">{{ post.title }}</a></p>
                            <p class="card-text">{{ post.post_info_summary }}</p>
                            <p class="card-text">Published on: {{post.created_date|date:"D M Y"}}</p>
                            <div class="card-text">
                                <div class="btn-group" role="group" aria-label="Basic example">
                                {% if user.is_authenticated and post.author == user %}
                                    <a href="{% url 'posts:post_remove' pk=post.pk%}" class="btn btn-outline-danger">Delete</a>
                                    <a href="{% url 'posts:post_edit' pk=post.pk%}" class="btn btn-outline-info">Edit</a>
                                {% endif %}
                                </div>
                            </div>
                            <br>
                            <p class="card-text"><a href="{% url 'comments:add_comment_to_post' pk=post.pk %}" class="btn btn-light">Add Comment</a></p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ post.likes.count }} Like{{ post.likes.count|pluralize }}
                            {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
                        </div>
                {% endif %}

                </div>

            </div>
                    {% if forloop.counter|divisibleby:"3" and not forloop.last %}
                </div><div class="row">
            {% endif %}

            <br>

        {% endfor %}


    </div>

{% else %}
        <div class="d-flex justify-content-center">
        <p>No Posts</p>
        </div>
{% endif %}


</div>

{% endblock %}