venv_twentythree/accounts/urls.py
from django.conf.urls import url, include
from accounts import views


app_name = 'accounts'

urlpatterns = [
    url(r'^profile_block/$', views.block_user, name='block_user'),
    url(r'^$', views.create_user_form, name='registration'),
    url(r'^list/$', views.search_users, name='list'),
    url(r'^profile/$', views.edit_profile, name='profile'),
    url(r'^craeateprofile$', views.crate_user_profile, name='createprofile'),
    url(r'^list/(?P<pk>\d+)/$', views.user_detail_view, name='detail'),
    url(r'^list_messages/(?P<pk>\d+)/$', views.user_detail_messages_view, name='detail_messages'),
    url(r'^viewprofile/$', views.UserProfileView.as_view(), name='viewprofile'),
    url(r'^confirm-deactivate/$', views.ConfirmDeactivate.as_view(), name='confirm-deactivate'),
    url(r'^deactivate/$', views.delete_profile, name='deactivate'),
    url(r'^accountsapi/$', views.UsersListAPI.as_view()),
    url(r'^accountsapi/(?P<pk>\d+)/$', views.UsersDetailAPI.as_view(), name='api_detail'),
    url(r'^acoountsapi/(?P<pk>\d+)/update/$', views.UserUpdateAPI.as_view(), name='api_update'),

]

venv_twentythree/comments/urls.py
from django.conf.urls import url
from comments import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'comments'

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^todo/(?P<pk>\d+)/suggestion/$', views.add_suggestion_to_todo, name='add_suggestion_to_todo'),
    url(r'^commentsapi/$', views.CommentListAPI.as_view()),
    url(r'^commentsapi/(?P<pk>\d+)/$', views.CommentDetailSeri.as_view(), name='api_detail'),
    url(r'^commentsapi/(?P<pk>\d+)/update/$', views.CommentUpdateSeri.as_view(), name='api_update'),
    url(r'^commentsapi/(?P<pk>\d+)/delete/$', views.CommentDeleteSeri.as_view(), name='api_delete')

]

venv_twentythree/noti/urls.py
from django.conf.urls import url
from noti import views
app_name = 'noti'

urlpatterns = [
    url(r'^$', views.AllNotificationsList.as_view(), name='all'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete')
]

venv_twentythree/todolist/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'todolist'

urlpatterns = [
    url(r'^$', views.world_todo_list, name='todo_list'),
    url(r'^my_todo$', views.addTodo, name='add'),
    url(r'^complete/(?P<pk>\d+)/$', views.complete_todo, name='complete'),
    url(r'^delete_complete/$', views.delete_completed, name='deletecomplete'),
    url(r'^delete_all/$', views.delete_all, name='deleteall'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserTodo.as_view(), name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.TodoDetailView.as_view(), name='single'),
    url(r'^remove/(?P<pk>\d+)/$', views.delete_individual_todo, name='remove_todo_individual'),


]

venv_twentythree/venv_twentythree/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('berenise90silvano90/', admin.site.urls),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^noti/', include('noti.urls', 'noti')),

    url(r'^group_message/', include('message_group.urls', namespace='group_message')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    url(r'^message/', include('mymessage.urls', namespace='message')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^todo/', include('todolist.urls', namespace='todo')),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^$', views.index_home.as_view(), name='home'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venv_twentythree/todolist/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Todo(models.Model):
    user = models.ForeignKey(User, related_name='wishes', on_delete=models.CASCADE)
    title = models.CharField(max_length=55)
    info = models.TextField(max_length=3000)
    todo_pic = models.ImageField(upload_to='media', blank=True)
    complete = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def meta_info_summary(self):
        len_info = len(self.info)
        if len_info > 480:
            return self.info[:480]+' . . . .continue'
        else:
            return self.info

    def meta_title_summary(self):
        len_title = len(self.title)
        if len_title >= 40:
            return self.title[:40]+'.....'
        else:
            return self.title

    def get_absolute_url(self):
        return reverse('todo:single', kwargs={'pk': self.pk, 'username': self.user.username})

    class Meta:
        ordering = ['-created_date']

venv_twentythree/todolist/forms.py
from django import forms
from .models import Todo
from django.forms import Textarea, TextInput, ImageField

class TodoForm(forms.ModelForm):
    class Meta:
        model = Todo
        fields = ('title', 'todo_pic', 'info')

        widgets = {
            'info': Textarea(attrs={'cols': 144, 'rows': 6, 'placeholder': 'info'}),
            'title': TextInput(attrs={'size': '48'})
        }


class TestingForm(forms.Form):
    image = forms.ImageField()

venv_twentythree/todolist/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, DeleteView, DetailView, ListView
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from django.http import Http404
from django.contrib import messages
from comments.models import Suggestion
from .models import Todo
User = get_user_model()
from posts.models import MakePost
from .forms import TodoForm, TestingForm
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from itertools import chain


@login_required
def addTodo(request):
    todo_list = Todo.objects.filter(user__exact=request.user)
    form = TodoForm()

    if request.method == "POST":
        form = TodoForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            user_todo_list = form.save(commit=False)
            get_title = form.cleaned_data['title']
            user_todo_list.user = request.user
            if_obj_exists = Todo.objects.filter(title=get_title, user__exact=request.user).exists()
            if if_obj_exists:
                messages.warning(request, 'Warning already in your list!')
                form = TodoForm()  # to clear form input
                return render(request, 'todolist/index.html', context={'form': form, 'todo_list': todo_list})
            else:
                user_todo_list.save()
                form = TodoForm()   # to clear form input
                return render(request, 'todolist/index.html', context={'form': form, 'todo_list': todo_list})

        else:
            return render(request, 'todolist/index.html', context={'form': form, 'todo_list': todo_list})
    else:
        context = {'todo_list': todo_list, 'form': form}
        return render(request, 'todolist/index.html', context)


@login_required
def complete_todo(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    user = request.user
    if user == todo.user:
        todo.complete = True
        todo.save()

    return redirect('todolist:add')


@login_required
def delete_completed(request):
    Todo.objects.filter(user__exact=request.user, complete__exact=True).delete()
    return redirect('todolist:add')


@login_required
def delete_all(request):
    Todo.objects.filter(user__exact=request.user).delete()

    return redirect('todolist:add')


class UserTodo(ListView, LoginRequiredMixin):

    context_object_name = 'todo_list'
    model = Todo
    template_name = 'todolist/user_todo_list.html'

    def get_queryset(self):
        try:
            self.todo_user = User.objects.prefetch_related('wishes').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.todo_user.wishes.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['todo_user'] = self.todo_user
        return context


class TodoDetailView(DetailView, LoginRequiredMixin):
    context_object_name = 'todo'
    model = Todo
    template_name = 'todolist/todo_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TodoDetailView, self).get_context_data(**kwargs)
        context['suggestion_list'] = Suggestion.objects.all().order_by('-created_date')
        return context


class TodoListView(ListView, LoginRequiredMixin):
    context_object_name = 'todo_list'
    template_name = 'todolist/todo_list.html'
    model = Todo


@login_required
def world_todo_list(request):
    queryset_list = Todo.objects.all()
    query = request.GET.get('q')
    if query is not None:
        queryset_list = queryset_list.filter(Q(title__icontains=query) | Q(info__icontains=query))

    paginator = Paginator(queryset_list, 6)    # Show 25 contacts per page

    page = request.GET.get('page')
    queryset = paginator.get_page(page)

    context = {
        "todo_list": queryset
    }
    return render(request, 'todolist/todo_list.html', context)


@login_required
def delete_individual_todo(request, pk):
    query = Todo.objects.filter(user__exact=request.user).get(pk=pk)

    query.delete()
    return redirect('todo:add')

venv_twentythree/todolist/templates/todolist/index.html
<!DOCTYPE html>
{% extends 'main.html' %}
{% load bootstrap4 %}
{% load static %}


{% block body_block %}

    <link rel="stylesheet" href="{% static 'css/my_style.css' %}" />


{% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}


<div class="container">
    <div class="jumbotron">

<div class="text-center"><h2>WHAT DO YOU WANT TO ADD TO YOUR META LIST?</h2></div>
<br>

        <form action="{% url 'todolist:add' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.title.id_for_label }}">Title: {{ form.title }}</label>
                <label for="{{ form.todo_pic.id_for_label }}"><input onchange="PreviewImage();" type="file" id="files" value="{{ form.todo_pic }}"></label>
                <img id="image" style="width: 170px; height: 200px; object-fit: cover" />
            </div>


            <p>{{ form.info }}</p>

            <button type="submit" class="btn btn-dark">ADD</button>
        </form>

        <br>
        <br>

<div class="d-flex justify-content-center">
        <a href="{% url 'todolist:deletecomplete' %}"><button type="button" class="btn btn-dark"> DELETE COMPLETED</button></a>
        <a href="{% url 'todolist:deleteall' %}"><button type="button" class="btn btn-danger">DELETE ALL</button></a>
</div>
        <br>
        <br>


         <div style="margin-left: 55px">
    <div class="row">
        {% for todo in todo_list %}
            <div class="col-md-3">
            <div class="card" style="width: 12rem; height: 12rem">
                {% if todo.complete %}

                <div class="card-body">
                    <p class="card-text"><a href="{% url 'todo:single' username=todo.user.username pk=todo.pk %}">{{ todo.meta_title_summary }}</a></p>
                    <button type="button" class="btn btn-success btn-lg btn-block">Completed</button>
                    <p class="card-link"></p><a href="{% url 'todo:remove_todo_individual' pk=todo.pk%}" class="btn btn-outline-danger">delete</a>
                </div>
                {% else %}
                <div class="card-body">
                    <p class="card-text"><a href="{% url 'todo:single' username=todo.user.username pk=todo.pk %}">{{ todo.meta_title_summary }}</a></p>
                    <p class="card-text"><a href="{% url 'todolist:complete' todo.pk %}" class="btn btn-outline-primary">Complete</a></p>
                    <p class="card-text"><a href="{% url 'todo:remove_todo_individual' pk=todo.pk %}" class="btn btn-outline-danger">delete</a></p>
                </div>
                            {% endif %}
            </div>


                        </div>
        {% if forloop.counter|divisibleby:"4" and not forloop.last %}
            </div><div class="row">
        {% endif %}
        {% endfor %}
           </div>
        </div>

    </div>
    </div>

 <script type="text/javascript">
        document.getElementById("files").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};
    </script>


{% endblock %}

venv_twentythree/todolist/templates/todolist/todo_confirm_delete.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}

    <div class="container">
        <div class="jumbotron">
            <div class="d-flex justify-content-center">

  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <input type="submit" value="Delete" class="btn btn-outline-danger">
  </form>
            </div>
        </div>
    </div>

{% endblock %}

venv_twentythree/todolist/templates/todolist/todo_detail.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}

<div class="container">
    <div class="card text-white bg-info mb-3">
    {% if todo.todo_pic %}
        <img class="card-img-top" src="{{ todo.todo_pic.url }}" alt="Card image cap">
    {% endif %}
        <div class="card-body">
            <p class="text-center">{{ todo.title }}</p>
            <p class="card-text">{{ todo.info }}</p>
            <p class="card-text">Completed: {{ todo.complete }}</p>
            <p class="card-title"><a href="{% url 'todo:for_user' username=todo.user.username %}" style="color: #1A01CC">@{{ todo.user.username }}</a></p>
            <p class="card-text">Published on: {{todo.created_date|date:"D M Y"}}</p>
            <p class="card-text"><a href="{% url 'comments:add_suggestion_to_todo' pk=todo.pk %}" class="btn btn-light">Add Suggestion</a></p>
            {% if user.is_authenticated and todo.user == request.user%}
        <a href="{% url 'todo:remove_todo_individual' pk=todo.pk %}" class="btn btn-danger">Remove</a>
    {% endif %}
        </div>
        <div class="card-footer text-muted">
            {{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}
        </div>
    </div>

</div>

<div class="container">
    <div class="jumbotron">
    <br>
    <div class="d-flex align-items-center flex-column">
    {% if todo.suggestions.count %}

    {% for suggestions in suggestion_list %}

        {% if suggestions.todo == todo %}
            <div class="card" style="width: 25rem;">
                <div class="card-body">
                    {% if request.user != suggestions.author%}
                    <p class="card-text"><a href="{% url 'accounts:detail' pk=suggestions.author.profiles.pk %}">{{ suggestions.author }}</a></p>
                        {% else %}
                        <p>{{ suggestions.author }}</p>
                        {% endif %}
                    <p class="card-text">Text: {{ suggestions.text }}</p>
                </div>
                <div class="card-footer text-muted"><p>Date: {{ suggestions.created_date }}</p>
                </div>
            </div>

            {% endif %}
    {% endfor %}
    </div>

    {% else %}
          <div class="container">
            <div align="center">
                <p><strong>No Suggestions</strong></p>
            </div>
        </div>
    {% endif %}

    </div>
</div>
{% endblock %}

venv_twentythree/todolist/templates/todolist/todo_list.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block body_block %}

<div class="jumbotron">



<div class="d-flex justify-content-center">

    <form method="GET" action="{% url 'todo:todo_list'%}" class="form-inline">
       {% csrf_token %}
        <div class="input-group input-group-lg">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup-sizing-lg">Search Metas</span>
            </div>
            <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="q">
            <button type="submit" class="btn btn-dark">GO</button>
        </div>
    </form>
</div>

    <br>


    <div class="row">

    {% for todo in todo_list %}
        <div class="col-md-4">

        <div class="card text-white bg-info mb-3">
            {% if todo.todo_pic %}
                <img class="card-img-top silvano" src="{{ todo.todo_pic.url }}" alt="Card image cap">

                <div class="card-body">
                    <p class="text-center"><a href="{% url 'todo:single' username=todo.user.username pk=todo.id %}" style="color: darkblue">{{ todo.title }}</a></p>
                    <p class="card-text" style="color: #080808">Completed: {{ todo.complete }}</p>
                    <p class="card-title"><a href="{% url 'todo:for_user' username=todo.user.username %}" style="color: darkblue">@{{ todo.user.username }}</a></p>
                </div>
                <div class="card-footer text-muted">
                    <p style="color: #2C2C2C">{{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}</p>
                </div>
            {% else %}
                <div class="card-body">
                    <p class="text-center"><a href="{% url 'todo:single' username=todo.user.username pk=todo.id %}" style="color: darkblue">{{ todo.title }}</a></p>
                    <p class="card-text" style="color: #080808">{{ todo.meta_info_summary }}</p>
                    <p class="card-text" style="color: #080808">Completed: {{ todo.complete }}</p>
                    <p class="card-title"><a href="{% url 'todo:for_user' username=todo.user.username %}" style="color: darkblue">@{{ todo.user.username }}</a></p>
                </div>
                <div class="card-footer text-muted">
                    <p style="color: #2C2C2C">{{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}</p>
                </div>
            {% endif %}
        </div>
        </div>
        {% if forloop.counter|divisibleby:"3" and not forloop.last %}
            </div><div class="row">
        {% endif %}
    {% endfor %}

    </div>


<div class="d-flex justify-content-center">

        <div class="pagination">

    {% if todo_list.has_other_pages %}

    {% if todo_list.has_previous %}
      <a href="?page={{ todo_list.previous_page_number }}" class="pagination_numbers">&laquo;</a>

    {% else %}
      <div class="disabled pagination_numbers" style="font-size: 20px"><span>&laquo;</span></div>

    {% endif %}

    {% for i in todo_list.paginator.page_range %}

      {% if todo_list.number == i %}
        <div class="pagination_numbers"><span> {{ i }} </span></div>


      {% else %}
        <a href="?page={{ i }}" class="pagination_numbers">{{ i }}</a>

      {% endif %}
    {% endfor %}

    {% if todo_list.has_next %}
      <a href="?page={{ todo_list.next_page_number }}" class="pagination_numbers">&raquo;</a>

    {% else %}
      <div class="disabled pagination_numbers"><span>&raquo;</span></div>

    {% endif %}


{% endif %}
    </div>

</div>

</div>
{% endblock %}

venv_twentythree/todolist/templates/todolist/user_todo_list.html
<!DOCTYPE html>
{% extends "main.html" %}

{% block serach_block %}
{% endblock %}

{% block body_block %}

<div class="jumbotron">

{%  if todo_list %}
    <div class="d-flex justify-content-center">
        <h2>{{ todo_user }}</h2>
    </div>
    <br>

    <div class="row">
        {% for todo in todo_list %}

            <div class="col-md-4">

                <div class="card text-white bg-info mb-3">
                    {% if todo.todo_pic %}
                        <img class="card-img-top silvano" src="{{ todo.todo_pic.url }}" alt="Card image cap">
                    <div class="card-body">
                        <p class="text-center"><a href="{% url 'todo:single' username=todo.user.username pk=todo.id %}" style="color: #1A01CC">{{ todo.title }}</a></p>
                        <p class="card-text" style="color: #2C2C2C">Completed: {{ todo.complete }}</p>
                        <p class="card-title" style="color: #2C2C2C">@{{ todo.user.username }}</p>
                        <p class="card-text" style="color: #2C2C2C">Published on: {{todo.created_date|date:"D M Y"}}</p>
                    </div>
                    <div class="card-footer text-muted">
                        <p style="color: #2C2C2C">{{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}</p>
                    </div>
                    {% else %}
                        <div class="card-body">
                            <p class="text-center"><a href="{% url 'todo:single' username=todo.user.username pk=todo.id %}" style="color: #1A01CC">{{ todo.title }}</a></p>
                            <p class="card-text" style="color: #2C2C2C">{{ todo.meta_info_summary }}</p>
                            <p class="card-text" style="color: #2C2C2C">Completed: {{ todo.complete }}</p>
                            <p class="card-title" style="color: #2C2C2C">@{{ todo.user.username }}</p>
                            <p class="card-text" style="color: #2C2C2C">Published on: {{todo.created_date|date:"D M Y"}}</p>
                        </div>
                        <div class="card-footer text-muted">
                            <p style="color: #2C2C2C">{{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}</p>
                        </div>
                    {% endif %}
                </div>
            </div>
    {% if forloop.counter|divisibleby:"3" and not forloop.last %}
    </div>
    <div class="row">
    {% endif %}

        {% endfor %}
    </div>
{% else %}
    <div class="d-flex justify-content-center">
    <p>No Metas</p>
    </div>
{% endif %}

</div>

{% endblock %}