venv_twentythree/accounts/urls.py
from django.conf.urls import url, include
from accounts import views


app_name = 'accounts'

urlpatterns = [
    url(r'^profile_block/$', views.block_user, name='block_user'),
    url(r'^$', views.create_user_form, name='registration'),
    url(r'^list/$', views.search_users, name='list'),
    url(r'^profile/$', views.edit_profile, name='profile'),
    url(r'^craeateprofile$', views.crate_user_profile, name='createprofile'),
    url(r'^list/(?P<pk>\d+)/$', views.user_detail_view, name='detail'),
    url(r'^list_messages/(?P<pk>\d+)/$', views.user_detail_messages_view, name='detail_messages'),
    url(r'^viewprofile/$', views.UserProfileView.as_view(), name='viewprofile'),
    url(r'^confirm-deactivate/$', views.ConfirmDeactivate.as_view(), name='confirm-deactivate'),
    url(r'^deactivate/$', views.delete_profile, name='deactivate'),
    url(r'^accountsapi/$', views.UsersListAPI.as_view()),
    url(r'^accountsapi/(?P<pk>\d+)/$', views.UsersDetailAPI.as_view(), name='api_detail'),
    url(r'^acoountsapi/(?P<pk>\d+)/update/$', views.UserUpdateAPI.as_view(), name='api_update'),

]

venv_twentythree/friends/urls.py
from django.conf.urls import url
from friends import views

app_name = 'friends'

urlpatterns = [
    url(r'^add/(?P<pk>\d+)/to_friends_list/$', views.add_friend_to_list, name='add_friend'),
    url(r'^view/(?P<username>[-\w]+)/friends_list/$', views.UserFriends.as_view(), name='my_list_friend'),
    url(r'^remove/(?P<pk>\d+)/$', views.delete, name='friend_remove'),

]

venv_twentythree/noti/urls.py
from django.conf.urls import url
from noti import views
app_name = 'noti'

urlpatterns = [
    url(r'^$', views.AllNotificationsList.as_view(), name='all'),
    url(r'^delete/(?P<pk>\d+)/$', views.delete, name='delete')
]

venv_twentythree/posts/urls.py
from django.conf.urls import url
from posts import views


app_name = 'posts'

urlpatterns = [
    url(r'^$', views.post_list_search, name='list'),
    url(r'^create_post/$', views.crate_post, name='create_post'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPosts.as_view(), name='for_user'),
    # url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='single'),

    # url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),

    url(r'^post/(?P<pk>\d+)$', views.post_details, name='post_detail'),
    url(r'^like/$', views.like_post, name='like_post'),

    url(r'^postsapi/$', views.PostListSeri.as_view()),
    url(r'^postsapi/create/$', views.PostCreateAPIView.as_view()),
    url(r'^postsapi/(?P<pk>\d+)/$', views.PostDetailSeri.as_view(), name='api_detail'),
    url(r'^postsapi/(?P<pk>\d+)/update/$', views.PostUpdateSeri.as_view(), name='api_update'),
    url(r'^postsapi/(?P<pk>\d+)/delete/$', views.PostDeleteSeri.as_view(), name='api_delete')
]

venv_twentythree/todolist/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'todolist'

urlpatterns = [
    url(r'^$', views.world_todo_list, name='todo_list'),
    url(r'^my_todo$', views.addTodo, name='add'),
    url(r'^complete/(?P<pk>\d+)/$', views.complete_todo, name='complete'),
    url(r'^delete_complete/$', views.delete_completed, name='deletecomplete'),
    url(r'^delete_all/$', views.delete_all, name='deleteall'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserTodo.as_view(), name='for_user'),
    url(r'^by/(?P<username>[-\w]+)/(?P<pk>\d+)/$', views.TodoDetailView.as_view(), name='single'),
    url(r'^remove/(?P<pk>\d+)/$', views.delete_individual_todo, name='remove_todo_individual'),


]

venv_twentythree/venv_twentythree/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls import url, include
from accounts import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('berenise90silvano90/', admin.site.urls),
    url(r'^notifications/', include('notify.urls', 'notifications')),
    url(r'^noti/', include('noti.urls', 'noti')),

    url(r'^group_message/', include('message_group.urls', namespace='group_message')),
    url(r'^friends/', include('friends.urls', namespace='friends')),
    url(r'^message/', include('mymessage.urls', namespace='message')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^todo/', include('todolist.urls', namespace='todo')),
    url(r'^login/$', LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
    url(r'^$', views.index_home.as_view(), name='home'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),
        name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venv_twentythree/templates/include_me.html
<!DOCTYPE html>


<div class="jumbotron">
    <div class="row">


        <div class="col">
            <div class="row">
        {% for todo in meta_list %}
            <div class="col-md-6">



                    <div class="card text-white bg-info mb-3">
            {% if todo.todo_pic %}
                <img class="card-img-top silvano" src="{{ todo.todo_pic.url }}" alt="Card image cap">

                <div class="card-body">
                    <p class="text-center"><a href="{% url 'todo:single' username=todo.user.username pk=todo.id %}" style="color: darkblue">{{ todo.title }}</a></p>
                    <p class="card-text" style="color: #080808">Completed: {{ todo.complete }}</p>
                    <p class="card-title"><a href="{% url 'todo:for_user' username=todo.user.username %}" style="color: darkblue">@{{ todo.user.username }}</a></p>
                </div>
                <div class="card-footer text-muted">
                    <p style="color: #2C2C2C">{{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}</p>
                </div>
            {% else %}
                <div class="card-body">
                    <p class="text-center"><a href="{% url 'todo:single' username=todo.user.username pk=todo.id %}" style="color: darkblue">{{ todo.title }}</a></p>
                    <p class="card-text" style="color: #080808">{{ todo.meta_info_summary }}</p>
                    <p class="card-text" style="color: #080808">Completed: {{ todo.complete }}</p>
                    <p class="card-title"><a href="{% url 'todo:for_user' username=todo.user.username %}" style="color: darkblue">@{{ todo.user.username }}</a></p>
                </div>
                <div class="card-footer text-muted">
                    <p style="color: #2C2C2C">{{ todo.suggestions.count }} suggestion{{ todo.suggestions.count|pluralize }}</p>
                </div>
            {% endif %}
        </div>


            </div>

            {% if forloop.counter|divisibleby:"2" and not forloop.last %}
            </div><div class="row">
            {% endif %}

        {% endfor %}

                </div>
        </div>



        <div class="col">
            <div class="row">
        {% for post in post_list %}
            <div class="col-md-6">


                            <div class="card text-white bg-dark mb-3">
                    {% if post.post_pic %}
                        <img class="card-img-top silvano" src="{{ post.post_pic.url }}" alt="Card image cap">
                        <div class="card-body">
                            <p class="text-center"><a href="{% url 'posts:post_detail' pk=post.id %}">{{ post.title }}</a></p>
                            <p class="card-text"><a href="{% url 'posts:for_user' username=post.author.username %}">@{{ post.author.username }}</a></p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ post.likes.count }} Like{{ post.likes.count|pluralize }}
                            {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
                        </div>
                    {% else %}
                        <div class="card-body">
                            <p class="text-center"><a href="{% url 'posts:post_detail' pk=post.id %}">{{ post.title }}</a></p>
                            <p class="card-text">{{ post.post_info_summary }}</p>
                            <p class="card-text"><a href="{% url 'posts:for_user' username=post.author.username %}">@{{ post.author.username }}</a></p>
                        </div>
                        <div class="card-footer text-muted">
                            {{ post.likes.count }} Like{{ post.likes.count|pluralize }}
                            {{ post.comments.count }} comment{{ post.comments.count|pluralize }}
                        </div>
                    {% endif %}
                </div>



            </div>

            {% if forloop.counter|divisibleby:"2" and not forloop.last %}
            </div><div class="row">
            {% endif %}

        {% endfor %}

                </div>

        </div>


     </div>

{#<div class="d-flex justify-content-center">#}
{##}
{#        <div class="pagination">#}
{##}
{#    {% if t_list.has_other_pages %}#}
{##}
{#    {% if t_list.has_previous %}#}
{#      <a href="?page={{ t_list.previous_page_number }}" class="pagination_numbers">&laquo;</a>#}
{##}
{#    {% else %}#}
{#      <div class="disabled pagination_numbers"><span>&laquo;</span></div>#}
{##}
{#    {% endif %}#}
{##}
{#    {% for i in t_list.paginator.page_range %}#}
{##}
{#      {% if t_list.number == i %}#}
{#        <div class="pagination_numbers"><span> {{ i }} </span></div>#}
{##}
{##}
{#      {% else %}#}
{#        <a href="?page={{ i }}" class="pagination_numbers">{{ i }}</a>#}
{##}
{#      {% endif %}#}
{#    {% endfor %}#}
{##}
{#    {% if t_list.has_next %}#}
{#      <a href="?page={{ t_list.next_page_number }}" class="pagination_numbers">&raquo;</a>#}
{##}
{#    {% else %}#}
{#      <div class="disabled pagination_numbers"><span>&raquo;</span></div>#}
{##}
{#    {% endif %}#}
{##}
{##}
{#{% endif %}#}
{#    </div>#}
{##}
{#</div>#}

</div>

venv_twentythree/templates/main.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap4 %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/main_style.css' %}"/>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% if user.is_authenticated %}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:list' %}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:todo_list'%}">Metas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'posts:create_post' %}" >Create post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'todo:add'%}">Add Meta</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ request.user.first_name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'posts:for_user' username=request.user %}">My Posts</a>
                        <a class="dropdown-item" href="{% url 'todo:for_user' username=request.user %}">My Metas</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Social
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'friends:my_list_friend' username=request.user %}">Friends</a>
                        <a class="dropdown-item" href="{% url 'group_message:my_message_members' username=request.user %}">Messages</a>
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'noti:all' %}">Notifications<span style="color: #3875d7"> {{ notifications_list.count }}</span></a>
                </li>


            {% if user.profiles %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Profile
                    </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'accounts:viewprofile' %}">View Profile</a>
                    <a class="dropdown-item" href="{% url 'accounts:profile' %}">Edit Profile</a>
                    <a class="dropdown-item" href="{% url 'accounts:confirm-deactivate' %}">Deactivate</a>
                </div>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:createprofile' %}">Create profile</a>
                </li>
            {% endif %}
            </ul>
                    <a class="nav-link" href="{% url 'logout' %}" >Logout</a>

            {% block serach_block %}
                <form method="GET" action="{% url 'accounts:list'%}" class="form-inline">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="text" placeholder="Search Users" aria-label="Search" name="q">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                 </form>
            {% endblock %}
        </div>
    {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>
            <a class="nav-link" href="{% url 'accounts:registration' %}">Register</a>
    {% endif %}





</nav>

    {% block body_block %}
        {% include 'include_me.html' %}

    {% endblock %}

</body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>